"""add adaptive_rules table and cpt_risk_config unique constraint

Revision ID: 998de30ca232
Revises: 
Create Date: 2026-05-12 08:32:19.475165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '998de30ca232'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adaptive_rules',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('rule_type', sa.String(length=64), nullable=False),
    sa.Column('payer_name', sa.String(length=256), nullable=False),
    sa.Column('cpt_code', sa.String(length=16), nullable=False),
    sa.Column('carc_code', sa.String(length=16), nullable=False),
    sa.Column('diagnosis_code', sa.String(length=16), nullable=False),
    sa.Column('rule_description', sa.Text(), nullable=False),
    sa.Column('fix_suggestion', sa.Text(), nullable=False),
    sa.Column('issue_type', sa.String(length=64), nullable=False),
    sa.Column('total_claims', sa.Integer(), nullable=True),
    sa.Column('denied_claims', sa.Integer(), nullable=True),
    sa.Column('denial_rate', sa.Float(), nullable=True),
    sa.Column('confidence_level', sa.String(length=8), nullable=True),
    sa.Column('severity', sa.String(length=8), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('threshold_value', sa.Float(), nullable=True),
    sa.Column('last_mined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('operator_approved', sa.Boolean(), nullable=True),
    sa.Column('operator_notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_type', 'payer_name', 'cpt_code', 'carc_code', 'diagnosis_code', name='uq_adaptive_rules_identity')
    )
    op.create_index('ix_adaptive_rules_confidence', 'adaptive_rules', ['confidence_level', 'severity'], unique=False)
    op.create_index('ix_adaptive_rules_payer_active', 'adaptive_rules', ['payer_name', 'is_active'], unique=False)
    op.create_unique_constraint('uq_cpt_risk_config_prefix', 'cpt_risk_config', ['cpt_prefix'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_cpt_risk_config_prefix', 'cpt_risk_config', type_='unique')
    op.drop_index('ix_adaptive_rules_payer_active', table_name='adaptive_rules')
    op.drop_index('ix_adaptive_rules_confidence', table_name='adaptive_rules')
    op.drop_table('adaptive_rules')
    # ### end Alembic commands ###
